flags:
    refresh_friends: true 
    first_link_only: false 
    max_quote_length: -1 
    qr_reload: "master_qr_code" 
    on_log_out: "command" 
    imgcat_qr: false 
    delete_on_edit: true 
    app_shared_link_mode: "image" 
    puid_logs: null 
    send_stickers_and_gif_as_jpeg: false 
    system_chats_to_include: "filehelper" 
    user_agent: null 
